CREATE TABLE AuditLog
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TableName NVARCHAR(50),
	ColName NVARCHAR(50),
	OldValue NVARCHAR(255),
	NewValue NVARCHAR(255),
	UpdatedAt DATETIME DEFAULT GETDATE()
);

ALTER TABLE Employe ADD Status NVARCHAR(50) DEFAULT 'ACTIF'
